booking/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root 'searches#show'

  namespace :admin do
    root 'admin#welcome#index'
    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_time, on: :member
    end
    resources :trains do
      resources :carriages
    end
    resources :welcome, only: [:index]
    resources :routes
    resources :tickets
  end
  resources :tickets
  resources :users
  resource :search, only: %i[new show edit create]
  resources :trains, only: %i[index show]
  resources :welcome
end

booking/app/controllers/admin/welcome_controller.rb
# frozen_string_literal: true

class Admin::WelcomeController < Admin::BasisController
  def index; end
end

booking/app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

booking/app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

booking/app/views/welcome/index.html.erb
<style>
  .head {
    text-align: center;
  }

  .buttons {
    text-align: center;
  }
</style>
<div class="head">
  <h1>Hello, RAILS!</h1>
</div>

<button> <%= link_to 'Sign In', users_path %> </button>

<div class="buttons">
  <button>  <%= link_to 'Railway Stations', railway_stations_path %>  </button>
  <button> <%= link_to 'Trains', trains_path %></button>
  <button> <%= link_to 'Routes', routes_path %> </button>
  <button> <%= link_to 'Tickets', tickets_path %> </button>
</div>