booking/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root 'searches#show'

  namespace :admin do
    root 'admin#welcome#index'
    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_time, on: :member
    end
    resources :trains do
      resources :carriages
    end
    resources :welcome, only: [:index]
    resources :routes
    resources :tickets
  end
  resources :tickets
  resources :users
  resource :search, only: %i[new show edit create]
  resources :trains, only: %i[index show]
  resources :welcome
end

booking/app/models/route.rb
# frozen_string_literal: true

class Route < ActiveRecord::Base
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes
  has_many :trains

  validate :stations_count
  validates :name, presence: true

  before_validation :set_name

  private

  def set_name
    self.name = "#{railway_stations.first.title} - #{railway_stations.last.title}"
  end

  scope :ordered_railway_stations, lambda {
    joins(:railway_stations_routes).order('railway_stations_routes.position')
  }

  scope :departure_railway_stations, lambda {
    joins(:railway_stations_routes).order('railway_stations_routes.departure')
  }

  scope :arrival_railway_stations, lambda {
    joins(:railway_stations_routes).order('railway_stations_routes.arrival')
  }

  def stations_count
    if railway_station_ids.count < 2
      errors.add(:base, 'Route must have minimum 2 station')
    end
  end
end

booking/app/controllers/admin/routes_controller.rb
# frozen_string_literal: true

class Admin::RoutesController < Admin::BasisController
  before_action :set_route, only: %i[show edit update destroy]

  def index
    @routes = Route.all
  end

  def show; end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to [:admin, @route]
    else
      render :new
    end
  end

  def edit; end

  def update
    if @route.update(route_params)
      redirect_to [:admin, @route]
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to admin_routes_path
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name, :current_train_id,
                                  railway_station_ids: [],
                                  train_ids: [])
  end
end

booking/app/controllers/routes_controller.rb
# frozen_string_literal: true

class RoutesController < ApplicationController
  before_action :set_route, only: %i[show edit update destroy]

  def index
    @routes = Route.all
  end

  def show; end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to @route
    else
      render :new
    end
  end

  def edit; end

  def update
    if @route.update(route_params)
      redirect_to @route
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to routes_path
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name, :current_train_id,
                                  railway_station_ids: [],
                                  train_ids: [])
  end
end

booking/app/views/admin/routes/_form.html.erb
<%= form_for([:admin, @route]) do |form| %>
  <% render 'common/errors', resource: @route %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label t('.stations') %>
    <%= form.collection_select :railway_station_ids,
                               RailwayStation.all, :id, :title, {}, { multiple: true } %>
  </div>

  <div class="actions">
    <%= form.submit t('.submit', action: @route.new_record? ? t('common.create') : t('common.edit'))%>
  </div>
<% end %>

booking/app/views/admin/routes/_route.html.erb
  <tr>
    <td><%= route.name %></td>
    <td><button><%= link_to t('common.show'), [:admin, route] %></button></td>
    <td><button><%= link_to t('common.edit'), edit_admin_route_path(route) %></button></td>
    <td><button><%= link_to t('common.delete'), [:admin,route], method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
  </tr>

booking/app/views/admin/routes/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', route: @route %>
<%= link_to t('common.back'), admin_routes_path %>

booking/app/views/admin/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%=t('.title') %></h1>

<table>
  <thead>
  <tr>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <%= render @routes %>
  </tbody>
</table>

<br>

<%= link_to t('.new'), new_admin_route_path %> |
<%= link_to t('common.back'), admin_welcome_index_path %>

booking/app/views/admin/routes/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', route: @route %>

<%= link_to t('common.back'), admin_routes_path %>

booking/app/views/admin/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('.title') %></strong>
  <%= @route.name %><br>
</p>

<% if @route.railway_stations.empty? %>
  <p>The route is not have any stations</p>
<% else %>
  <p>The route have the stations:</p>
  <table>
    <thead>
    <tr>
      <td width='100px'> <%=t('.name') %></td>
      <td> <%=t('.position') %></td>
      <td><%=t('.departure') %></td>
      <td> <%=t('.arrival') %></td>
    </tr>
    </thead>
    <tbody>
    <% @route.railway_stations.ordered.each do |station| %>
      <tr>
        <td><%= station.title %> </td>
        <td>
          <%= form_tag update_position_admin_railway_station_path(station), method: :patch do %>
            <%= number_field_tag :position, station.position_in(@route) %>
            <%= hidden_field_tag :route_id, @route.id %>
            <%= submit_tag t('common.edit') %>
          <% end %>
        </td>
        <td>
          <%= form_tag update_time_admin_railway_station_path(station), method: :patch do %>
            <%= time_field_tag :departure, station.time(@route, :departure) %>
            </td>
            <td>
              <%= time_field_tag :arrival, station.time(@route, :arrival) %>
              <%= hidden_field_tag :route_id, @route.id %>
              <%= submit_tag t('common.edit') %>
          <% end %>
          </td>
          </tr>
    <% end %>
    </tbody>
  </table>
<% end %>
<% if @route.trains.empty? %>
  <p><%=t('.no_trains') %> </p>
<% else %>
  <p><%=t('.trains_on_route') %></p>
  <ul>
    <% @route.trains.each do |train| %>
      <li><%= train.number %></li>
    <% end %>
  </ul>
<% end %>


<%= link_to t('common.edit'), edit_admin_route_path(@route) %> |
<%= link_to  t('common.back'), admin_routes_path %> |
<%= link_to  t('common.main'), admin_welcome_index_path %>