booking/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root 'searches#show'

  namespace :admin do
    root 'admin#welcome#index'
    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_time, on: :member
    end
    resources :trains do
      resources :carriages
    end
    resources :welcome, only: [:index]
    resources :routes
    resources :tickets
  end
  resources :tickets
  resources :users
  resource :search, only: %i[new show edit create]
  resources :trains, only: %i[index show]
  resources :welcome
end

booking/app/models/carriage.rb
# frozen_string_literal: true

class Carriage < ApplicationRecord
  TYPES = %w[CoupeCarriage CVCarriage ReservedCarriage SeatingCarriage].freeze
  belongs_to :train
  validates :number, :type, presence: true
  validates :number, uniqueness: { scope: :train_id }

  before_validation :add_number

  scope :reserved, -> { where(type: 'ReservedCarriage') }
  scope :seating, -> { where(type: 'SeatingCarriage') }
  scope :coupe, -> { where(type: 'CoupeCarriage') }
  scope :sv, -> { where(type: 'SVCarriage') }
  scope :ordered, -> { order(:number) }

  private

  def add_number
    self.number ||= max_number + 1
  end

  def max_number
    train.carriages.pluck(:number).max || 0
  end
end

booking/app/controllers/admin/carriages_controller.rb
# frozen_string_literal: true

class Admin::CarriagesController < Admin::BasisController
  before_action :set_carriage, only: %i[show edit update destroy]
  before_action :set_train

  def index
    @carriages = Carriage.all
  end

  def show; end

  def new
    @carriage = Carriage.new
  end

  def create
    @carriage = @train.carriages.new(carriage_params)

    if @carriage.save
      redirect_to [:admin, @train]
    else
      render :new
    end
  end

  def edit; end

  def update
    if @carriage.update(carriage_params)
      redirect_to @carriage.becomes(Carriage)
      redirect_to admin_train_carriage_path(@carriage)
    else
      render :edit
    end
  end

  def destroy
    @carriage.destroy
    redirect_to admin_train_path
  end

  private

  def set_train
    @train = Train.find(params[:train_id])
  end

  def set_carriage
    @carriage = Carriage.find(params[:id])
  end

  def carriage_params
    params.require(:carriage).permit(:number, :train_id, :type, :top_seats,
                                     :lower_seats, :side_lower_seats,
                                     :side_top_seats)
  end
end

booking/app/views/admin/carriages/_carriage.html.erb
<tr>
  <td><%= carriage.number %></td>
  <td><%= link_to 'Show',  admin_train_carriage_path(@train, carriage) %></td>
  <td><%= link_to 'Edit', edit_admin_train_carriage_path(@train, carriage) %></td>
  <td><%= link_to 'Destroy', admin_train_carriage_path(@train,carriage), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

booking/app/views/admin/carriages/_coupe_carriage.html.erb
<p>
  <strong>Top seats:</strong>
  <%= @carriage.top_seats %>
</p>

<p>
  <strong>Lower seats:</strong>
  <%= @carriage.lower_seats %>
</p>

booking/app/views/admin/carriages/_form.html.erb
<h1> New Carriage </h1>

<%= form_for [:admin, @train, @carriage.becomes(Carriage)] do |form| %>
  <%= render 'common/errors', resource: @carriage %>

  <div class="field">
    <%= form.label :train, "Train" %>
    <%= form.collection_select :train_id,
                               Train.all, :id, :number %>
  </div>

  <div class="field">
    <%= form.label :number, "Carriage number" %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :type, "Type" %>
    <%= form.select(:type, %w(CoupeCarriage ReservedCarriage SVCarriage
        SeatingCarriage)) %>
  </div>

  <div class="field">
    <%= form.label :lower_seats %>
    <%= form.text_field :lower_seats %>
  </div>
  <div class="field">
    <%= form.label :top_seats %>
    <%= form.text_field :top_seats %>
  </div>
  <div class="field">
    <%= form.label :side_lower_seats %>
    <%= form.text_field :side_lower_seats %>
  </div>
  <div class="field">
    <%= form.label :side_top_seats %>
    <%= form.text_field :side_top_seats %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

booking/app/views/admin/carriages/_reserved_carriage.html.erb
<p>
  <strong>Top seats:</strong>
  <%= @carriage.top_seats %>
</p>

<p>
  <strong>Lower seats:</strong>
  <%= @carriage.lower_seats %>
</p>

<p>
  <strong>Side lower seats:</strong>
  <%= @carriage.side_lower_seats %>
</p>

<p>
  <strong>Side top seats:</strong>
  <%= @carriage.side_top_seats %>
</p>

booking/app/views/admin/carriages/_seating_carriage.html.erb
<p>
  <strong>Lower seats:</strong>
  <%= @carriage.lower_seats %>
</p>

booking/app/views/admin/carriages/_sv_carriage.html.erb
<p>
  <strong>Lower seats:</strong>
  <%= @carriage.lower_seats %>
</p>

booking/app/views/admin/carriages/edit.html.erb
<h1>Update Carriage</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_train_carriages_path %>
<%= link_to 'Main', root_path %>

booking/app/views/admin/carriages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carriages</h1>

<table>
  <thead>
  <tr>
    <th>Number</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <%= render partial: 'carriage', collection: @carriages %>

  </tbody>
</table>

<br>

<%= link_to 'New Carriage', new_admin_train_carriage_path %> |
<%= link_to 'Back', admin_welcome_index_path %>

booking/app/views/admin/carriages/new.html.erb
<h1>Carriages</h1>

<%= render 'form' %>

<%= link_to 'New Carriage', new_admin_train_carriage_path(@train) %> |
<%= link_to 'Back', admin_train_carriages_path %>

booking/app/views/admin/carriages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @carriage.id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @carriage.type %>
</p>

<strong>Train:</strong>
<% if @carriage.train %>
  <%= @carriage.train.number %>
<% else %>
  No train
<% end %>

<% if @carriage.top_seats %>
  <p>
    <strong>Top Seats</strong>
    <%= @carriage.top_seats %>
  </p>
<% end %>

<% if @carriage.lower_seats %>
  <p>
    <strong>Lower Seats</strong>
    <%= @carriage.lower_seats %>
  </p>
<% end %>

<% if @carriage.side_top_seats %>
  <p>
    <strong>Side Top Seats</strong>
    <%= @carriage.side_top_seats %>
  </p>
<% end %>

<% if @carriage.side_lower_seats %>
  <p>
    <strong>Side Lower Seats</strong>
    <%= @carriage.side_lower_seats %>
  </p>
<% end %>


<%= link_to 'Edit', edit_admin_train_carriage_path(@carriage.becomes(Carriage)) %> |
<%= link_to 'Back', admin_train_carriages_path %> |
<%= link_to 'Menu', admin_welcome_index_path %>