booking/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root 'searches#show'

  namespace :admin do
    root 'admin#welcome#index'
    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_time, on: :member
    end
    resources :trains do
      resources :carriages
    end
    resources :welcome, only: [:index]
    resources :routes
    resources :tickets
  end
  resources :tickets
  resources :users
  resource :search, only: %i[new show edit create]
  resources :trains, only: %i[index show]
  resources :welcome
end

booking/app/models/train.rb
# frozen_string_literal: true

class Train < ApplicationRecord
  validates :number, presence: true
  validates :number, format: /[a-z\d]{3}-?[a-z\d]{2}/i.freeze

  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_railway_station_id
  belongs_to :route, class_name: 'Route', foreign_key: :route_id
  has_many :tickets
end

booking/app/controllers/admin/trains_controller.rb
# frozen_string_literal: true

class Admin::TrainsController < Admin::BasisController
  before_action :set_train, only: %i[show edit update destroy]

  def index
    @trains = Train.all
  end

  def show; end

  def new
    @train = Train.new
  end

  def edit; end

  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to [:admin, @train], notice: 'Train was successfully created.'
    else
      render :new
    end
  end

  def update
    if @train.update(train_params)
      redirect_to [:admin, @train], notice: 'Train was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @train.destroy
    redirect_to admin_trains_path, notice: 'Train was successfully destroyed.'
  end

  private

  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number, :current_railway_station_id,
                                  :route_id, :order_carriage)
  end
end

booking/app/controllers/trains_controller.rb
# frozen_string_literal: true

class TrainsController < ApplicationController
  before_action :set_train, only: %i[show edit update destroy]

  # GET /trains
  # GET /trains.json
  def index
    @trains = Train.all
  end

  # GET /trains/1
  # GET /trains/1.json
  def show; end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit; end

  # POST /trains
  # POST /trains.json
  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to @train, notice: 'Train was successfully created.' }
        format.json { render :show, status: :created, location: @train }
      else
        format.html { render :new }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1
  # PATCH/PUT /trains/1.json
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to @train, notice: 'Train was successfully updated.' }
        format.json { render :show, status: :ok, location: @train }
      else
        format.html { render :edit }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to trains_url, notice: 'Train was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_train
    @train = Train.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def train_params
    params.require(:train).permit(:number, :current_railway_station_id,
                                  :route_id)
  end
end

booking/app/helpers/trains_helper.rb
# frozen_string_literal: true

module TrainsHelper
end

booking/app/views/admin/trains/_carriage.html.erb
<li><%= link_to "Carriage #{carriage.number}", new_admin_train_carriage_path(@train) %></li>

booking/app/views/admin/trains/_form.html.erb
<%= form_for([:admin, @train]) do |form| %>
  <% render 'common/errors', resource: @train %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :current_railway_station_id, 'Station' %>
    <%= form.collection_select :current_railway_station_id,
                               RailwayStation.all, :id, :title %>
  </div>

  <div class="field">
    <%= form.label :current_route_id, 'Route' %>
    <%= form.collection_select :route_id,
                               Route.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :order_carriages %>
    <%= form.check_box :order_carriages%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

booking/app/views/admin/trains/_train.html.erb
<tr>
  <td><%= train.number %></td>
  <td> <button><%= link_to 'Show', [:admin,train] %> </button> </td>
  <td> <button> <%= link_to 'Edit', edit_admin_train_path(train) %></button></td>
  <td> <button> <%= link_to 'Destroy', [:admin, train], method: :delete, data: { confirm: 'Are you sure?' } %> </button></td>
</tr>

booking/app/views/admin/trains/edit.html.erb
<h1>Editing Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Back', admin_trains_path %>

booking/app/views/admin/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trains</h1>

<table>
  <thead>
  <tr>
    <th>Number</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <%= render @trains %>
  </tbody>
</table>

<br>

<%= link_to 'New Train', new_admin_train_path %> |
<%= link_to 'Menu', admin_welcome_index_path %>

booking/app/views/admin/trains/new.html.erb
<h1>New Train</h1>

<%= render 'form', train: @train %>

 <%= link_to 'Back', admin_trains_path %>

booking/app/views/admin/trains/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Number:</strong>
  <%= @train.number %>
</p>
<p>
  <strong>Railway Station:</strong>
  <% if @train.current_station %>
    <%= @train.current_station.title %>
  <% else %>
    No station
  <% end %>
</p>
<%= render partial: 'carriage', collection: @train.order_carriages %>

<strong>Coupe
  cars: <%= @train.count_cars(@train.carriages, 'CoupeCarriage') %></strong>
<p>Lower
  seats: <%= @train.count_seats('CoupeCarriage', 'lower_seats') %></p>
<p>Top
  seats: <%= @train.count_seats('CoupeCarriage', 'top_seats') %></p>

<strong>Reserve
  cars: <%= @train.count_cars(@train.carriages, 'ReserveCarriage') %></strong>
<p>Lower
  seats: <%= @train.count_seats('ReservedCarriage', 'lower_seats') %></p>
<p>Top
  seats: <%= @train.count_seats('ReservedCarriage', 'top_seats') %></p>
<p>Side Lower
  seats: <%= @train.count_seats('ReservedCarriage', 'side_lower_seats') %></p>
<p>Side Top
  seats: <%= @train.count_seats('ReservedCarriage', 'side_top_seats') %></p>

<strong>Seating
  cars: <%= @train.count_cars(@train.carriages, 'SeatingCarriage') %></strong>
<p>Lower
  seats: <%= @train.count_seats('SeatingCarriage', 'lower_seats') %></p>

<strong>SV
  cars: <%= @train.count_cars(@train.carriages, 'SVCarriage') %></strong>
<p>Lower
  seats: <%= @train.count_seats('SVCarriage', 'lower_seats') %></p>

<p>
  <strong>Route:</strong>
  <% if @train.route %>
    <%= @train.route.name %>
  <% else %>
    No route
  <% end %>
</p>

<%= link_to 'Add carriage', new_admin_train_carriage_path(@train) %> |
<%= link_to 'Edit', edit_admin_train_path(@train) %> |
<%= link_to 'Back', admin_trains_path %> |
<%= link_to 'Menu', admin_welcome_index_path %>